# Generated by Django 5.1 on 2024-08-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pseudo', models.CharField(default='aka0102', max_length=10, unique=True)),
                ('Mot_de_passe', models.CharField(default='azerty', max_length=100)),
                ('Creat_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pseudo', models.CharField(default='aka0102', max_length=10, unique=True)),
                ('Mot_de_passe', models.CharField(default='azerty', max_length=100)),
            ],
        ),
    ]
