# Generated by Django 5.1 on 2024-08-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(default='Féminin', max_length=30)),
                ('Class', models.CharField(default='Non-spécifiée', max_length=30)),
                ('Registration', models.CharField(default='01D022526', max_length=30)),
                ('Age', models.CharField(default='2000/10/01', max_length=30)),
                ('Number', models.CharField(default='00000000', max_length=30)),
                ('City', models.CharField(default='Non-spécifiée', max_length=30)),
            ],
        ),
    ]
